/* Replace with your SQL commands */

CREATE TABLE "orderProduct" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int
);


ALTER TABLE "orderProduct" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "orderProduct" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");