/* Replace with your SQL commands */

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "status" varchar
);

ALTER TABLE "order" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
